# Import Headers

In [1]:
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
import os

load_dotenv()

True

# Setup LLM

In [2]:
api_key = os.getenv("OPENAI_API_KEY")
llm = ChatOpenAI(model_name="gpt-3.5-turbo", temperature=0)

response = llm.invoke("Write a SQL query to get top 5 customers by sales. keep it short")
print(response.content)

SELECT customer_id, SUM(sales_amount) as total_sales
FROM sales
GROUP BY customer_id
ORDER BY total_sales DESC
LIMIT 5;


# Connect With Database

In [3]:
from langchain.utilities import SQLDatabase

db_user = "root"
db_password = "root"
db_host = "localhost"
db_name = "tshirts"

db = SQLDatabase.from_uri(f"mysql+pymysql://{db_user}:{db_password}@{db_host}/{db_name}",sample_rows_in_table_info=3)

# print(db.table_info)

______________

# Ask questions with Zero shot learning

In [4]:
from langchain.agents import create_sql_agent

sql_agent = create_sql_agent(llm, db=db, agent_type="zero-shot-react-description") # set verbose=True to check how it thinks

## Question 1

In [5]:
q1 = sql_agent.invoke("How many t-shirts do we have left for Nike in extra small size and white color?")
print(q1)

{'input': 'How many t-shirts do we have left for Nike in extra small size and white color?', 'output': '1'}


- ##### `1` is incorrect. The correct answer is `25`.

## Question 2

In [6]:
q2 = sql_agent.invoke("How much is the price of the inventory for all small size t-shirts?")
print(q2)

{'input': 'How much is the price of the inventory for all small size t-shirts?', 'output': 'The prices of the inventory for all small size t-shirts are 17, 44, 37, 27, 25, 50, 48, 18, and 39.'}


- ##### It has returned prices of small sized randomn coloured tshirts. The correct answer is `$13,429`.

# Question 3

In [7]:
q3 = sql_agent.invoke("If we have to sell all the Levi’s T-shirts today with discounts applied. How much revenue our store will generate (post discounts)?")
print(f"Input:\n{q3['input']}\nOutput:\n{q3['output']}")

Input:
If we have to sell all the Levi’s T-shirts today with discounts applied. How much revenue our store will generate (post discounts)?
Output:
$1212.60


- ##### `$1,212.60` is incorrect. The correct answer is `$12,147$`.

# Question 4

In [8]:
q4 = sql_agent.invoke("If we have to sell all the Levi’s T-shirts today with discounts applied. How much revenue our store will generate (post discounts)?")
print(q4)

{'input': 'If we have to sell all the Levi’s T-shirts today with discounts applied. How much revenue our store will generate (post discounts)?', 'output': 'The store will generate a revenue of $5578 post discounts if all the Levi’s T-shirts are sold today.'}


- ##### `$5,578` is incorrect. The correct answer is `$12,946`.

# Question 5

In [9]:
q5 = sql_agent.invoke("How many white color Levi's t shirts we have available?")
print(q5)

{'input': "How many white color Levi's t shirts we have available?", 'output': '2'}


- ##### `2` is incorrect. The correct answer is `5`.

_____________________

# Provide correct SQL queries and get the results

In [10]:
q1 = sql_agent.invoke("select * from t_shirts Where brand = 'Nike' AND color = 'White' and size = 'XS'")
q2 = sql_agent.invoke("SELECT SUM(price*stock_quantity) FROM t_shirts WHERE size = 'S'")
q3 = sql_agent.invoke("""
    select sum(a.total_amount * ((100-COALESCE(discounts.pct_discount,0))/100)) as total_revenue from
    (select sum(price*stock_quantity) as total_amount, t_shirt_id from t_shirts where brand = 'Levi'
    group by t_shirt_id) a left join discounts on a.t_shirt_id = discounts.t_shirt_id
     """)
q4 = sql_agent.invoke("SELECT SUM(price * stock_quantity) FROM t_shirts WHERE brand = 'Levi'")
q5 = sql_agent.invoke("SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Levi' AND color = 'White'")

print(f"Q1 Output: {q1}")
print(f"Q2 Output: {q2}")
print(f"Q3 Output: {q3}")
print(f"Q4 Output: {q4}")
print(f"Q5 Output: {q5}")

Q1 Output: {'input': "select * from t_shirts Where brand = 'Nike' AND color = 'White' and size = 'XS'", 'output': "(82, 'Nike', 'White', 'XS', 14, 25)"}
Q2 Output: {'input': "SELECT SUM(price*stock_quantity) FROM t_shirts WHERE size = 'S'", 'output': "The total value of size 'S' t-shirts in stock is $13,429."}
Q3 Output: {'input': "\n    select sum(a.total_amount * ((100-COALESCE(discounts.pct_discount,0))/100)) as total_revenue from\n    (select sum(price*stock_quantity) as total_amount, t_shirt_id from t_shirts where brand = 'Levi'\n    group by t_shirt_id) a left join discounts on a.t_shirt_id = discounts.t_shirt_id\n     ", 'output': '$12,147.60'}
Q4 Output: {'input': "SELECT SUM(price * stock_quantity) FROM t_shirts WHERE brand = 'Levi'", 'output': '$12,956'}
Q5 Output: {'input': "SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Levi' AND color = 'White'", 'output': '43'}


__________________